### ISSUE TITLE
接下来我们需要回答关于libcontainer的一些问题

### ISSUE THREAD

**Issue by nvagus** [lazdongshi/firstreport#1]
libcontainer向上提供了什么接口？
libcontainer向下如何组织cgroup？
libcontainer向下如何组织namespace？
libcontainer向下如何组织capabilities？
rootfs的文件系统的特点？
libcontainer的缺点是什么？
每人领三个问题。

**Comment by Osinovsky** [comment]
我领这三个
> libcontainer向下如何组织cgroup？
>libcontainer向下如何组织namespace？
>libcontainer向下如何组织capabilities？

**Comment by Osinovsky** [comment]
这个站文章挺全的
[http://www.infoq.com/cn/](InfoQ)

**Comment by Osinovsky** [comment]
这个站文章挺全的
[InfoQ](http://www.infoq.com/cn/)

**Comment by ralzq01** [comment]
我领这三个
libcontainer向上提供了什么接口？
rootfs的文件系统的特点？
libcontainer的缺点是什么？

**Comment by ralzq01** [comment]
docs.docker.com 里面有一些开发文档和 API 文档，可以做下参考
